# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dominsok_1.0.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 842)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(310, 80, 671, 601))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.pizzaTab = QtWidgets.QWidget()
        self.pizzaTab.setObjectName("pizzaTab")
        self.pizzaName = QtWidgets.QLabel(self.pizzaTab)
        self.pizzaName.setGeometry(QtCore.QRect(10, 10, 181, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pizzaName.sizePolicy().hasHeightForWidth())
        self.pizzaName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pizzaName.setFont(font)
        self.pizzaName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pizzaName.setObjectName("pizzaName")
        self.pizzaImg = QtWidgets.QPushButton(self.pizzaTab)
        self.pizzaImg.setGeometry(QtCore.QRect(10, 50, 181, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pizzaImg.sizePolicy().hasHeightForWidth())
        self.pizzaImg.setSizePolicy(sizePolicy)
        self.pizzaImg.setMouseTracking(True)
        self.pizzaImg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pizzaImg.setObjectName("pizzaImg")
        self.pizzaPrice = QtWidgets.QLabel(self.pizzaTab)
        self.pizzaPrice.setGeometry(QtCore.QRect(10, 230, 181, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pizzaPrice.sizePolicy().hasHeightForWidth())
        self.pizzaPrice.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pizzaPrice.setFont(font)
        self.pizzaPrice.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pizzaPrice.setObjectName("pizzaPrice")
        self.tabWidget.addTab(self.pizzaTab, "")
        self.sideTab = QtWidgets.QWidget()
        self.sideTab.setObjectName("sideTab")
        self.tabWidget.addTab(self.sideTab, "")
        self.beverageTab = QtWidgets.QWidget()
        self.beverageTab.setObjectName("beverageTab")
        self.tabWidget.addTab(self.beverageTab, "")
        self.topFrame = QtWidgets.QFrame(self.centralwidget)
        self.topFrame.setGeometry(QtCore.QRect(10, 0, 971, 81))
        self.topFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.topFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.menuLabel = QtWidgets.QLabel(self.topFrame)
        self.menuLabel.setGeometry(QtCore.QRect(460, 30, 351, 51))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.menuLabel.setFont(font)
        self.menuLabel.setTextFormat(QtCore.Qt.AutoText)
        self.menuLabel.setObjectName("menuLabel")
        self.graphBt = QtWidgets.QPushButton(self.topFrame)
        self.graphBt.setGeometry(QtCore.QRect(910, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.graphBt.setFont(font)
        self.graphBt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graphBt.setAutoFillBackground(False)
        self.graphBt.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Playdata/Desktop/graphico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphBt.setIcon(icon)
        self.graphBt.setAutoDefault(False)
        self.graphBt.setDefault(False)
        self.graphBt.setFlat(False)
        self.graphBt.setObjectName("graphBt")
        self.logoBt = QtWidgets.QPushButton(self.topFrame)
        self.logoBt.setGeometry(QtCore.QRect(10, 0, 271, 81))
        self.logoBt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logoBt.setAutoFillBackground(False)
        self.logoBt.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Py_Workspace/dominsuk/pizza/logo1.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoBt.setIcon(icon1)
        self.logoBt.setIconSize(QtCore.QSize(250, 300))
        self.logoBt.setAutoDefault(True)
        self.logoBt.setFlat(True)
        self.logoBt.setObjectName("logoBt")
        self.checkFrame = QtWidgets.QFrame(self.centralwidget)
        self.checkFrame.setGeometry(QtCore.QRect(10, 80, 291, 601))
        self.checkFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.checkFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.checkFrame.setObjectName("checkFrame")
        self.label = QtWidgets.QLabel(self.checkFrame)
        self.label.setGeometry(QtCore.QRect(0, 10, 291, 51))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.checkFrame)
        self.label_2.setGeometry(QtCore.QRect(0, 350, 291, 51))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setObjectName("label_2")
        self.checkBt = QtWidgets.QPushButton(self.checkFrame)
        self.checkBt.setGeometry(QtCore.QRect(10, 470, 271, 61))
        font = QtGui.QFont()
        font.setFamily("KoPubWorld돋움체 Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBt.setFont(font)
        self.checkBt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBt.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.checkBt.setCheckable(False)
        self.checkBt.setObjectName("checkBt")
        self.cancelBt = QtWidgets.QPushButton(self.checkFrame)
        self.cancelBt.setGeometry(QtCore.QRect(10, 540, 271, 61))
        font = QtGui.QFont()
        font.setFamily("KoPubWorld돋움체 Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cancelBt.setFont(font)
        self.cancelBt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelBt.setStyleSheet("font: 75 12pt \"KoPubWorld돋움체 Bold\";\n"
"background-color: rgb(255, 85, 127);")
        self.cancelBt.setCheckable(False)
        self.cancelBt.setObjectName("cancelBt")
        self.totalLcd = QtWidgets.QLCDNumber(self.checkFrame)
        self.totalLcd.setGeometry(QtCore.QRect(10, 410, 241, 51))
        self.totalLcd.setObjectName("totalLcd")
        self.label_3 = QtWidgets.QLabel(self.checkFrame)
        self.label_3.setGeometry(QtCore.QRect(260, 430, 21, 31))
        font = QtGui.QFont()
        font.setFamily("KoPubWorldDotum")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.checkTable = QtWidgets.QTableWidget(self.checkFrame)
        self.checkTable.setGeometry(QtCore.QRect(0, 60, 291, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkTable.sizePolicy().hasHeightForWidth())
        self.checkTable.setSizePolicy(sizePolicy)
        self.checkTable.setObjectName("checkTable")
        self.checkTable.setColumnCount(2)
        self.checkTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.checkTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.checkTable.setHorizontalHeaderItem(1, item)
        self.bottomFrame = QtWidgets.QFrame(self.centralwidget)
        self.bottomFrame.setGeometry(QtCore.QRect(10, 690, 951, 111))
        self.bottomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomFrame.setObjectName("bottomFrame")
        self.bannerLabel = QtWidgets.QLabel(self.bottomFrame)
        self.bannerLabel.setGeometry(QtCore.QRect(3, 0, 951, 111))
        self.bannerLabel.setText("")
        self.bannerLabel.setPixmap(QtGui.QPixmap("../Py_Workspace/dominsuk/pizza/pizza.png"))
        self.bannerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bannerLabel.setObjectName("bannerLabel")
        self.bottomFrame.raise_()
        self.tabWidget.raise_()
        self.topFrame.raise_()
        self.checkFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 984, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pizzaName.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">pizzaName</p></body></html>"))
        self.pizzaImg.setText(_translate("MainWindow", "pizzaImg"))
        self.pizzaPrice.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">pizzaPrice</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pizzaTab), _translate("MainWindow", "PIZZA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sideTab), _translate("MainWindow", "SIDE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.beverageTab), _translate("MainWindow", "BERVERAGE"))
        self.menuLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">PIZZA</p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">총 주문 내역</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">TOTAL</span></p></body></html>"))
        self.checkBt.setText(_translate("MainWindow", "결 제 하 기"))
        self.cancelBt.setText(_translate("MainWindow", "취 소 하 기"))
        self.label_3.setText(_translate("MainWindow", "원"))
        item = self.checkTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "메뉴"))
        item = self.checkTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "가격"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

